### ISSUE TITLE
Option to limit number of shown decimals / rounding

### ISSUE THREAD

**Issue by Minnowo** [you-apps/CalcYou#16]
### Describe your suggested feature

If you type `5 % 6`, you will get something like `0.3000000000000000004`, ideally you could say round to 5 decimal, and would instead get `0.30000`.

My initial thought would be a drop down menu in the top right opposite the hamburger menu. This would keep it relatively reachable from the main page and be pretty easy to use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VasilisKos** [comment]
I think the initial request was the option to globally choose the number of decimal digits.
