### ISSUE TITLE
It would have been more intuitive to have tabs rather then a menu

### ISSUE THREAD

**Issue by heckarman** [you-apps/CalcYou#20]
### Describe your suggested feature

As said in the title, this would require a partial rewrite of the app.
The existing way of the app to work feels non-intuitive and non user friendly to access your conversion and other features.

It would be great if you could modify it such that by means of swipe you current the nude to unit conversion.

### Other details

Reference `calculator-inator` on f-droid

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
Swiping is already used to access the scientific calculator, so this wouldn't work. A bottom navigation bar would work, but I doubt it would look good here. So the current implementation is the best choice IMO. I disagree that the navigation drawer is not user friendly, it's used almost everywhere and therefore quite intuitive. I'd close this but Suhas will decide. BTW changing the navigation form doesn't require a rewrite.
