### ISSUE TITLE
availabke in F-droid?

### ISSUE THREAD

**Issue by saona-raimundo** [you-apps/CalcYou#22]
### Describe your suggested feature

I am new to foss in android, but is it possible to add or apply to be in F-droid?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We've already submitted the app and are currently waiting for feedback from the F-Droid team.

**Comment by julianfairfax** [comment]
> We've already submitted the app and are currently waiting for feedback from the F-Droid team.

The F-Droid team is currently waiting for a new Calc You release before they approve its entry into the F-Droid repo. ([Source](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14173#note_1710547874))
