### ISSUE TITLE
horizontal screen orientation

### ISSUE THREAD

**Issue by fukiame** [you-apps/CalcYou#25]
### Steps to reproduce

1. switch device orientation
2. see the result

### Expected behavior

an usable ui

### Actual behavior

![Screenshot_20240113-200121_CalcYou](https://github.com/you-apps/CalcYou/assets/122709956/96f05ce4-752d-45fd-a0ae-57695287cb20)

### Calc You version

1.0, downloaded from GitHub Releases

### Android version

Android 14 UQ1A.240105.004

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DominikHracek** [comment]
Same happend to me, you could add that in horizontal mode, there're more options (like more scientific/advaned calculator(like with sin, cos, tg, root, exponent, etc.))
