### ISSUE TITLE
Please add AC button and C button

### ISSUE THREAD

**Issue by friosrhy** [you-apps/CalcYou#36]
### Describe your suggested feature

It clears the calculator, almost every other has this and it is very useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
⌫ button is clear (C) and long pressing ⌫ button will clear all (AC)

**Comment by friosrhy** [comment]
Thank you for the clarification

Sent from Proton Mail Android

-------- Original Message --------
