### ISSUE TITLE
unmeant line break in menu (german language)

### ISSUE THREAD

**Issue by FiSHYsolutions** [you-apps/CalcYou#38]
### Steps to reproduce

just open the app and use the german language

![2024-04-26_17-05](https://github.com/you-apps/CalcYou/assets/222112/4957352a-25eb-43ab-a003-a7b520b64f57)

used display => 6.7 in (170.18 mm)
used resolution => 1080 x 2400 (392 PPI)

### Expected behavior

"Einheitenumwandler" without linebreak

### Actual behavior

"Einheitenumwandler" with linebreak

### Calc You version

1.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can edit the translations yourself here: https://hosted.weblate.org/projects/you-apps/calc-you/

**Comment by FiSHYsolutions** [comment]
"Einheitenrechner" is fine and should do the job.
