### ISSUE TITLE
Floating & Tile calculator

### ISSUE THREAD

**Issue by VasilisKos** [you-apps/CalcYou#41]
### Describe your suggested feature

It'd be very convenient to add the following features: 
1. A floating calculator, over other apps, when tapping the home button. 
2. A quick settings tile, opening the app. 
This way the use of the calculator when using other apps, like e.g. the web browser or the phone, would be much easier. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think it's really worth adding these suggestions, like what would it be useful for?

**Comment by VasilisKos** [comment]
> I don't think it's really worth adding these suggestions, like what would it be useful for?

Like I said, the use of the calculator when using other apps, like e.g. the web browser or the phone, would be much easier. Now the only way to do that is either by splitting the screen in two or by using the task manager. The first one is not supported by your app (I'll open a feature request for that). So, literally this app doesn't support using it along with other apps, which is a very often scenario. For example, when using Chrome and need a calculator at the same time.

**Comment by Bnyro** [comment]
Sorry, that's out of scope for the app due to the fact that it takes a lot of efforts compared to the usefulness.

Split screen should be used in such scenarios (your other issue).

**Comment by VasilisKos** [comment]
OK. That's up to you. Thanks anyway for the great app. 😉
