### ISSUE TITLE
Graphing Capabilities

### ISSUE THREAD

**Issue by kaafir786** [you-apps/CalcYou#51]
### Describe your suggested feature

Basic graphing capabilities inbuilt with app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already implemented on main branch.
