### ISSUE TITLE
+-*/ can automatically give the result

### ISSUE THREAD

**Issue by oplle** [you-apps/CalcYou#53]
### Describe your suggested feature

Very good experience
+
history for calculations #40

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, it often doesn't make sense to show results in between and it's also not that user friendly if a user makes a typo / presses the wrong number.
