### ISSUE TITLE
Can't calculate negative value in temperature calculator

### ISSUE THREAD

**Issue by kdh8219** [you-apps/CalcYou#56]
### Steps to reproduce

1. Goto temperature calculator
2. We can't type negative sign(-)
3. And also we can't calculate it when paste it
![Screenshot_20240720_201556_CalcYou](https://github.com/user-attachments/assets/a3290f97-bc07-4167-8800-571d384884fd)

### Expected behavior

We should be able to type it and calculate it.

### Actual behavior

We can't.

### Calc You version

1.2(f-droid)

### Android version

Android 4 + One UI 6.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not reproducible on all my devices, please try using a different keyboard.
