### ISSUE TITLE
Date and Time Category

### ISSUE THREAD

**Issue by Creeperman3000** [you-apps/CalcYou#58]
### Expected Behaviour
Introduce a new "Date and Time" category in the sidebar to enhance time-related calculations and comparisons.

### Current Behaviour
Currently, there is no "Date and Time" category in the sidebar.

#### Features:
- Display an overview of pinned timezones, showing the current time, offset from UTC (e.g., +0), and associated famous cities.
- Allow users to search and pin timezones, making them easily accessible in the overview.
- Users can unpin timezones and customise the famous cities associated with each timezone.

#### Default Setup:
- **Timezone 1**: User’s current location (highlighted).
- **Timezone 2**: User’s home timezone (empty by default).
- **Timezone 3**: UTC (only displayed if it differs from the other timezones).

#### Features:
- Provide a simple calculator for adding or subtracting time values.
- Allow users to input custom time values for calculation.

#### Default Setup:
- **Time 1**: Current time.
- **Time 2**: Empty (user input required).
- **Mode**: Addition (default), with an option to switch to subtraction.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I'm not requesting to add a new unit converter or to modify an existing one.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Although this seems somewhat reasonable, the text still looks very AI generated and thus is rejected.

**Comment by Creeperman3000** [comment]
@Bnyro 
The text was AI-generated to help with readability because I am bad at writing, but I assure you, I am not a bot. I genuinely believe this feature is valuable and would improve the app’s usability.

**Comment by Bnyro** [comment]
Feel free to create a new well-explaining issue, but without the use of AI.

You may use translators if that makes things easier for you, but the use of generative AI is just disrespecting.
